# do some inital setup tasks on a new fedora server vm
# updated Nov 2025
# tested on Fedora 43 Server Edition

#recommended fedora server software setup :
# - custom + guest agents + common networkmanager submodules + standard

# you might have to ssh to the host first to accept the key into your known hosts

# to run : 
# ansible-playbook -i your_server_ip, -u andrew --ask-pass --ask-become-pass fedora-server-initial-setup.yml

- name: Configure Fedora server
  hosts: all
  become: yes
  
  vars_prompt:
    - name: "public_key"
      prompt: "Enter the public SSH key"
      private: no

  tasks:
    - name: Ensure user exists and has wheel
      user:
        name: "{{ ansible_user }}"
        state: present
        groups: wheel
        append: yes

    - name: Add public key to the user
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ public_key }}"

    # this way only SSH key auth is allowed
    - name: Disable SSH password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: Disable SELinux
      selinux:
        state: disabled

    # optional as cockpit may not be installed
    - name: Ensure Cockpit service is stopped
      ansible.builtin.systemd:
        name: cockpit.socket
        state: stopped
      ignore_errors: yes

    # optional as cockpit may not be installed
    - name: Ensure Cockpit does not start at boot
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: no
      ignore_errors: yes

    - name: Extend the logical volume
      community.general.lvol:
        vg: fedora
        lv: root
        size: +100%FREE

    - name: Extend the XFS filesystem
      community.general.filesystem:
        fstype: xfs
        dev: /dev/fedora/root
        resizefs: yes

    - name: Update all packages
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Reboot the server
      reboot:

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
